version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: securepay
      POSTGRES_PASSWORD: securepass
      POSTGRES_DB: securepay_db
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - secure-net
  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: your_jwt_secret_key # Cambiar por una contraseña supersegura
      DB_HOST: db
      DB_USER: securepay
      DB_PASSWORD: securepass
      DB_NAME: securepay_db
    depends_on:
      - db
    networks:
      - secure-net
  transfer-service:
    build: ./transfer-service
    ports:
      - "3001:3001"
    environment:
      JWT_SECRET: your_jwt_secret_key # Cambiar por una contraseña supersegura
      DB_HOST: db
      DB_USER: securepay
      DB_PASSWORD: securepass
      DB_NAME: securepay_db
    depends_on:
      - db
      - auth-service
    networks:
      - secure-net
  networks:
    secure-net:
      driver: bridge # Red aislada: Los servicios no se ven desde el exterior, solo vía Gateway